### ISSUE TITLE
Problem with make Shv: 

### ISSUE THREAD

**Issue by IJ1TI** [robertobucher/LinuxLabo#1]
After running make Shv, i get this error: 

[ 47%] Building CXX object clients/jn50view/CMakeFiles/jn50view.dir/jn50view_autogen/mocs_compilation.cpp.o
In file included from /home/jt/Develop/SHV/shvapp/build/clients/jn50view/jn50view_autogen/UVLADIE3JM/moc_dlgapplog.cpp:11,
                 from /home/jt/Develop/SHV/shvapp/build/clients/jn50view/jn50view_autogen/mocs_compilation.cpp:2:
/home/jt/Develop/SHV/shvapp/build/clients/jn50view/jn50view_autogen/UVLADIE3JM/../../../../../clients/jn50view/src/dlgapplog.h:4:10: fatal error: QDialog: No such file or directory
    4 | #include \<QDialog>
      |          ^~~~~~~~~
compilation terminated.
make[3]: *** [clients/jn50view/CMakeFiles/jn50view.dir/build.make:87: clients/jn50view/CMakeFiles/jn50view.dir/jn50view_autogen/mocs_compilation.cpp.o] Error 1
make[3]: Leaving directory '/home/jt/Develop/SHV/shvapp/build'
make[2]: *** [CMakeFiles/Makefile2:1348: clients/jn50view/CMakeFiles/jn50view.dir/all] Error 2
make[2]: Leaving directory '/home/jt/Develop/SHV/shvapp/build'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/home/jt/Develop/SHV/shvapp/build'
make: *** [Makefile:73: Shv] Error 2

running qtchooser -print-env i get: 
QT_SELECT="default"
QTTOOLDIR="/usr/lib/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu"

Tried on WSL2. 
Probably more Shv related then here. 
Also - is Shv optionall or necessary for running pysimCoder?

**Comment by robertobucher** [comment]
Shv is not required to run pysimCoder. It is useful if you want to change the variables on the fly when the generated code is running I can try to reproduce your problem.Best regardsRobertoInviato dal mio Galaxy
-------- Messaggio originale --------Da: IJ1TI ***@***.***> Data: 19/09/24  14:28  (GMT+01:00) A: robertobucher/LinuxLabo ***@***.***> Cc: Subscribed ***@***.***> Oggetto: [robertobucher/LinuxLabo] Problem with make Shv:  (Issue #1) 
After running make Shv, i get this error:
[ 47%] Building CXX object clients/jn50view/CMakeFiles/jn50view.dir/jn50view_autogen/mocs_compilation.cpp.o
In file included from /home/jt/Develop/SHV/shvapp/build/clients/jn50view/jn50view_autogen/UVLADIE3JM/moc_dlgapplog.cpp:11,
from /home/jt/Develop/SHV/shvapp/build/clients/jn50view/jn50view_autogen/mocs_compilation.cpp:2:
/home/jt/Develop/SHV/shvapp/build/clients/jn50view/jn50view_autogen/UVLADIE3JM/../../../../../clients/jn50view/src/dlgapplog.h:4:10: fatal error: QDialog: No such file or directory
4 | #include 
|          ^~~~~~~~~
compilation terminated.
make[3]: *** [clients/jn50view/CMakeFiles/jn50view.dir/build.make:87: clients/jn50view/CMakeFiles/jn50view.dir/jn50view_autogen/mocs_compilation.cpp.o] Error 1
make[3]: Leaving directory '/home/jt/Develop/SHV/shvapp/build'
make[2]: *** [CMakeFiles/Makefile2:1348: clients/jn50view/CMakeFiles/jn50view.dir/all] Error 2
make[2]: Leaving directory '/home/jt/Develop/SHV/shvapp/build'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/home/jt/Develop/SHV/shvapp/build'
make: *** [Makefile:73: Shv] Error 2
running qtchooser -print-env i get:
QT_SELECT="default"
QTTOOLDIR="/usr/lib/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu"
Tried on WSL2.
Probably more Shv related then here.
Also - is Shv optionall or necessary for running pysimCoder?

**Comment by Cuvy95** [comment]
i have the same Problem, how can i run pysimCoder without Shv, when i do make pysimcoder and then run "pysimCoder", 
nothing happend, what do i wrong and how can i run pysimcoder without Shv
Thanks for your great Work, i hope i can use PysimCoder as alternatetiv for simulink

**Comment by robertobucher** [comment]
SHV is only mrequired if you need to change parameters "on-the-fly" during execution of the RT generated code.

To run pysimCoder you need that some paths are right configured in your machine: look at your .bashrc file and check if you have the following lines (instead of /home/bucher/CACSD you have your installation path):

....
export PYSUPSICTRL=/home/bucher/CACSD/pysimCoder
export PYEDITOR=emacs
export PYTHONPATH=/home/bucher/Documents/PYTHON:/home/bucher/CACSD/pysimCoder/resources/blocks/rcpBlk
......

Check the "link" under /usr/local/bin:

lrwxrwxrwx 1 root   root         55 May 14 10:59 configLibs -> /home/bucher/CACSD/pysimCoder/BlockEditor/configLibs.py
lrwxrwxrwx 1 root   root         53 May 14 10:59 dataplot -> /home/bucher/CACSD/pysimCoder/BlockEditor/dataplot.py
lrwxrwxrwx 1 root   root         54 May 14 10:59 defBlocks -> /home/bucher/CACSD/pysimCoder/BlockEditor/defBlocks.py
-rwxr-xr-x 1 root   root         77 May 14 10:59 gen_pydev
lrwxrwxrwx 1 root   root         47 May 14 10:59 loadnrt -> /home/bucher/CACSD/pysimCoder/DriverNRT/loadnrt
lrwxrwxrwx 1 root   root         65 May 10 07:42 pjintf -> /home/bucher/CACSD/pysimCoder/BlockEditor/PlotJugglerInterface.py
lrwxrwxrwx 1 root   root         53 May 14 10:59 pyParams -> /home/bucher/CACSD/pysimCoder/BlockEditor/pyParams.py
lrwxrwxrwx 1 root   root         53 May 14 10:59 xblk2Blk -> /home/bucher/CACSD/pysimCoder/BlockEditor/xblk2Blk.py

In order to launch pysimCoder you have to launch:

$ /home/bucher/CACSD/pysimCoder/pysim-run.sh
check again the path to substitute /home/bucher/CACSD/

I hope this helps

We haven't checked SHV under WSL (we prefer a lot to work on Linux machines...)

**Comment by Cuvy95** [comment]
I work with Linux Mint and use the Ubuntu installer.

I have now done this steps, when i now try to run pysimCoder i git this Message:
5.15.2
Traceback (most recent call last):
  File "/home/name/LinuxLabo-master/Develop/pysimCoder/BlockEditor/pysimCoder.py", line 8, in <module>
    from supsisim.library import Library
  File "/home/Name/LinuxLabo-master/Develop/pysimCoder/toolbox/supsisim/supsisim/library.py", line 9, in <module>
    from supsisim.pyEdit import NewEditorMainWindow
  File "/home/Name/LinuxLabo-master/Develop/pysimCoder/toolbox/supsisim/supsisim/pyEdit.py", line 10, in <module>
    from supsisim.editor import Editor
  File "/home/Name/LinuxLabo-master/Develop/pysimCoder/toolbox/supsisim/supsisim/editor.py", line 11, in <module>
    from supsisim.client import *
  File "/home/Name/LinuxLabo-master/Develop/pysimCoder/toolbox/supsisim/supsisim/client.py", line 6, in <module>
    from shv import RpcUrl, SimpleClient, RpcError, SHVType
ModuleNotFoundError: No module named 'shv'

I dont know what i have to do now to run pysimcoder
I hope you can help me :)

**Comment by robertobucher** [comment]
You're right! This happens because of the last development in Prague. It should be checked with a try/except method...

Perhaps you can try to install pyshv (simply with "pip install pyshv")

But It doesn't appear as an error ! I'll check pysimCoder for this.

**Comment by Cuvy95** [comment]
Nice it worked :)
So for all other users with this problem:
You dont have to make Shv, you only have to make pysimcoder and then pip install pyshv, then go to the installation path and double cklick at "pysim-run.sh" Then it will be open

Big thanks for your help

**Comment by robertobucher** [comment]
Thanks for the check! I'll modify the 2 Makefile (Debian and Ubuntu) in order to fix the problem!
